### ISSUE TITLE
register_address untangle

### ISSUE THREAD

**Issue by broskoTT** [tenstorrent/tt-umd#104] opened 2024-10-03 09:18 UTC
The function register_address is clearly aarch specific, but this is hidden under some ifelses on bar spaces.
Refactor these functions (in TTDevice/PCIDevice), make them clearly arch specific and easier to read.

**Comment by pjanevskiTT** [comment] 2024-11-05 15:58
Duplicate of #63, closing this

**Closed by pjanevskiTT** 2024-11-05 15:58 UTC
Labels: api redesign
